apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: default
type: Opaque
stringData:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: djnagoconnect
  DB_USER: root
  DB_PASSWORD: <Password> # No '' will be added before and after