# Generated by Django 5.2.1 on 2025-06-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
