# Generated by Django 5.2.1 on 2025-07-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file_path',
            new_name='file',
        ),
    ]
