# Generated by Django 4.2 on 2025-08-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_file_path_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
