# Generated by Django 4.2 on 2025-08-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_participant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='fiscal_year',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
