# Generated by Django 4.2 on 2026-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_training_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
