# Generated by Django 4.2 on 2026-07-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_training_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='organizer',
        ),
        migrations.AddField(
            model_name='batch',
            name='organizer',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
